# baseURL = 'https://example.org/'
# languageCode = 'en-us'
# title = 'The Karnian Web'

baseurl      = "localhost"
title        = "TheKarnianWeb"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Chingaderas al azar, vamos!!!1!1"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = true

  # Metadata mostly used in document's head
  description = "NNenennww"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "The Karnian Web"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  [languages.en.params]
    subtitle  = "TKW"

    [languages.en.params.logo]
    #  logoText = "TKW <-"
    #  logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
      path = "/img/Ra.png"
    # alt = "Your example logo alt text"
      alt = "K"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
  [[menu.main]]
    identifier = "music"
    name       = "Music!"
    url        = "/music"
  [[menu.main]]
    identifier = "products"
    name       = "Products"
    url        = "/products"
  
  
  [languages.es]
    title = "The Karnian Web"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"
